name: Test python

on:
  push:
    tags: [ "*" ]
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

jobs:
  test-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Core Dump
        id: in_coredmp
        run: |
          git clone https://github.com/gaogaotiantian/coredumpy
          pip install -r coredumpy/requirements-dev.txt
          cd coredumpy && make build && make install
      
      - name: Checkout
        run: |
          python main.py
          ls
      - name: Upload Dump file
        uses: actions/upload-artifact@v4
        with:
          name: Dump_File
          path: |
            dumps